#!/usr/bin/python

file = '/home/ybusel/july16/dns' 
 n_record = str(raw_input("Please enter new dns record: ")) 
 with open(file) as f: 
 
for line in f: 
 		if n_record in line : 
 
 			print "Record %s exists" %(n_record)  
 			 
 			break 
 
 #		if not found : 
 	else: 
 
 			print "Record does not exist" 
