#!/usr/bin/python

f = open('/path/to/file','r')
lines = []
for index, text in enumerate(f):
# Choose lines to be printed ####
     if 2 <= index <= 10:
             lines.append(text)
             print (text)
#             print lines
# or another way to do that: 
#file = f.readlines()
#line = file[line number]
#print line

f.close()
